# Generated by Django 4.2.30 on 2026-06-06 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='진료과명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '진료과',
                'verbose_name_plural': '진료과',
            },
        ),
        migrations.CreateModel(
            name='EmergencyKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True, verbose_name='응급 키워드')),
                ('category', models.CharField(blank=True, max_length=30, verbose_name='분류')),
            ],
            options={
                'verbose_name': '응급 키워드',
                'verbose_name_plural': '응급 키워드',
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_text', models.CharField(max_length=300, verbose_name='증상 입력')),
                ('recommended_dept', models.CharField(max_length=50, verbose_name='추천 진료과')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='검색 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '증상 검색 이력',
                'verbose_name_plural': '증상 검색 이력',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='병원명')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('open_time', models.TimeField(verbose_name='진료 시작')),
                ('close_time', models.TimeField(verbose_name='진료 종료')),
                ('departments', models.ManyToManyField(related_name='hospitals', to='api.department', verbose_name='진료과목')),
            ],
            options={
                'verbose_name': '병원',
                'verbose_name_plural': '병원',
            },
        ),
        migrations.CreateModel(
            name='SymptomKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='증상 키워드')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='가중치')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_keywords', to='api.department', verbose_name='진료과')),
            ],
            options={
                'verbose_name': '증상 키워드',
                'verbose_name_plural': '증상 키워드',
                'unique_together': {('keyword', 'department')},
            },
        ),
    ]
