# Generated by Django 4.2.30 on 2026-06-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='건강보험심사평가원 진료과목코드(dgsbjtCd). 예: 01=내과, 13=이비인후과', max_length=2, null=True, unique=True, verbose_name='HIRA 진료과목코드'),
        ),
    ]
