# Generated by Django 4.2.30 on 2026-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ykiho',
            field=models.CharField(blank=True, help_text='심평원 API 연동용 식별자. 상세정보(진료시간 등) 조회에 사용', max_length=200, null=True, unique=True, verbose_name='암호화 요양기호'),
        ),
    ]
