# Generated by Django 4.2.30 on 2026-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospital_ykiho'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='sat_close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='토요일 종료'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sat_open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='토요일 시작'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sun_close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='일요일 종료'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sun_open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='일요일 시작'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='close_time',
            field=models.TimeField(verbose_name='평일 진료 종료'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='open_time',
            field=models.TimeField(verbose_name='평일 진료 시작'),
        ),
    ]
