# Generated by Django 4.2.30 on 2026-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hospital_sat_close_time_hospital_sat_open_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpid', models.CharField(max_length=20, unique=True, verbose_name='기관코드')),
                ('name', models.CharField(max_length=100, verbose_name='기관명')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='대표전화')),
                ('er_phone', models.CharField(blank=True, max_length=20, verbose_name='응급실 전화')),
                ('emcls_name', models.CharField(blank=True, max_length=40, verbose_name='응급의료기관 분류')),
            ],
            options={
                'verbose_name': '응급의료기관',
                'verbose_name_plural': '응급의료기관',
            },
        ),
    ]
