# Generated by Django 4.2.30 on 2026-06-22 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_emergencycenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='별점')),
                ('content', models.TextField(blank=True, verbose_name='후기')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='도움돼요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.department', verbose_name='방문 진료과')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.hospital', verbose_name='병원')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '병원 후기',
                'verbose_name_plural': '병원 후기',
                'ordering': ['-created_at'],
                'unique_together': {('hospital', 'user')},
            },
        ),
    ]
