# Generated by Django 4.2.30 on 2026-06-22 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hospitalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='feedback',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='추천 평가'),
        ),
        migrations.CreateModel(
            name='KeywordFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='정규화 키워드')),
                ('score', models.IntegerField(default=0, verbose_name='누적 피드백 점수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_feedbacks', to='api.department', verbose_name='진료과')),
            ],
            options={
                'verbose_name': '추천 피드백 학습값',
                'verbose_name_plural': '추천 피드백 학습값',
                'unique_together': {('keyword', 'department')},
            },
        ),
    ]
