# Generated by Django 4.2.30 on 2026-06-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_symptomlog_feedback_keywordfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomkeyword',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='표시용 증상명'),
        ),
    ]
