# Generated by Django 4.2.30 on 2026-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_symptomkeyword_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='source',
            field=models.CharField(default='rule', max_length=10, verbose_name='추천 출처'),
        ),
    ]
