# Generated by Django 4.2.30 on 2026-06-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_symptomlog_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordfeedback',
            options={'verbose_name': '추천 피드백 보정값', 'verbose_name_plural': '추천 피드백 보정값'},
        ),
    ]
